import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#41414d",
  },
  backButton: {
    position: "absolute",
    top: 60,
    left: 24,
    width: 64,
    height: 44,
    padding: 10,
    borderRadius: 7,
    textAlign: "center",
    color: "#f0f0f5",
    backgroundColor: "#ff9c01",
    shadowColor: "#f0f0f5",
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 2,
    shadowRadius: 5,
    zIndex: 99,
  },
  content: {
    marginTop: 80,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    zIndex: 1,
  },
  title: {
    fontFamily: "RuslanDisplay_400Regular",
    color: "#f0f0f5",
    textAlign: "center",
    textShadowColor: "green",
    textShadowOffset: { width: -1, height: 1 },
    textShadowRadius: 10,
    marginBottom: 20,
  },
  description: {
    fontSize: 18,
    textAlign: "center",
    color: "#f5870a",
    fontFamily: "Roboto_500Medium",
    paddingHorizontal: 20,
    marginBottom: 20,
    opacity: 0.8,
  },
  tutorialTitle: {
    fontFamily: "Roboto_500Medium",
    fontSize: 24,
    fontWeight: "bold",
    color: "#f5870add",
    marginTop: 20,
    marginBottom: 15,
  },
  steps: {
    fontSize: 16,
    alignSelf: 'flex-start',
    color: "#f5f5f0",
    paddingHorizontal: 20,
    marginBottom: 10,
    fontFamily: "Roboto_500Medium",
  },
  bold: {
    fontWeight: "bold",
    color: "#f5870a",
    fontSize: 20,
  },
});
